# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [33]:
N = int(input("Количество хоббитов: "))
K = int(input("Количество кусков хлеба: "))
def share_bread(N, K):
    x = K // N
    y = K % N
    return x, y
print(share_bread(N, K))
assert share_bread(N=3, K=14) == (4, 2)

Количество хоббитов: 5
Количество кусков хлеба: 78
(15, 3)


## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [32]:
year = int(input('Год: '))
def leap_year(year):
    if year % 400 == 0:
        tex_result = 'YOU SHALL PASS'
    elif year % 4 == 0 and year % 100 != 0:
        tex_result = 'YOU SHALL PASS'
    else:
        tex_result = 'YOU SHALL NOT PASS'
    return tex_result
print(leap_year(year))
assert leap_year(5) == 'YOU SHALL NOT PASS'

Год: 258
YOU SHALL NOT PASS


## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [14]:
a = float(input('a: '))
b = float(input('b: '))
c = float(input('c: '))
def amulet_area(a, b, c):
    p = (a+b+c)*0.5
    S = round(((p*(p-a)*(p-b)*(p-c)) ** 0.5), 2)
    return S
print("Площадь амулета равна", (amulet_area(a,b,c)))
assert amulet_area(3, 4, 5) == 6

a: 5
b: 6
c: 7
Площадь амулета равна 14.7


## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [52]:
import numpy as np

def cal_euclidean(a, b):    
    sqr = np.square(a - b)
    sqr_sum = np.sum(sqr)
    distance = round((np.sqrt(sqr_sum)), 2)
    return distance

def cal_manhattan(a, b):
    modul = abs(a - b)
    distance = np.sum(modul)
    return distance

def cal_cosine(a, b):
    ch = np.dot(a, b)
    zn = np.linalg.norm(a) * np.linalg.norm(b)
    distance = round(1 - np.divide(ch, zn), 4)
    return distance

In [53]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print('Евклидово расстояние:', cal_euclidean(a, b))
print('Расстояние Манхэттена:', cal_manhattan(a, b))
print('Косинусное расстояние:', cal_cosine(a, b)) # почему косинусное расстояние при других вводных больше 1?

Евклидово расстояние: 22.56
Расстояние Манхэттена: 57
Косинусное расстояние: 0.6154


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в интервале от 0 до 1 остаются прежними

In [9]:
my_array = np.random.rand(100)
my_array = list(my_array)

if 0.0 not in my_array:
    my_array.insert(0, 0)
    my_array.pop()
else:
    print(np.min(my_array))

if 1.0 not in my_array:
    my_array.pop()
    my_array.insert(99, 1)
else:
    print(np.max(my_array))

print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0, 0.8354748444875961, 0.7183094546488192, 0.42513632398530476, 0.9713466686697367, 0.1521317519443668, 0.06953593708736427, 0.7071932512503506, 0.29715170032080207, 0.4015269828963587, 0.27851757462891835, 0.5119888894891313, 0.07736907488691824, 0.6093969127553873, 0.5337181942768326, 0.012448993011068166, 0.4851682336353934, 0.424252168014455, 0.6076453322172312, 0.378866969148671, 0.18031409061064863, 0.35550792502201944, 0.5959128068425188, 0.6436334404109536, 0.6741246193765185, 0.24964630787039999, 0.7975378985620913, 0.13962284188045604, 0.1499622295411509, 0.6161898312116372, 0.43309421266136106, 0.5295323113000777, 0.19045080785118296, 0.7764453178815268, 0.6400742713370163, 0.4255322591357731, 0.6911158147743176, 0.7189084466655563, 0.4645248185388423, 0.34712804691718036, 0.6459896289642366, 0.24092742904275777, 0.5599915893809891, 0.6444795637093795, 0.31605251100735265, 0.5871531143705516, 0.25809689747459175, 0.799914615135763, 0.9810026709531129, 0.809396732196

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [16]:
# Это было сложно. Может я не догадалась до кого-то простого и очевидного решения? Подскажите! Спасибо.

import numpy as np

my_array = np.random.randint(0,51, size=(5, 6)) #5 rows 6 columns
maxi = np.argmax(my_array)
maxi_index = np.unravel_index(maxi, [5, 6])
selected_column = my_array[:, maxi_index[1]] # rows [0], columns [1]

print(my_array)
print(selected_column)

[[13 42  5 47 50 17]
 [49  5 27 44 11 18]
 [39 33 14 44 45 29]
 [43 19 21  2 24 28]
 [16 36 33 39  2  6]]
[50 11 45 24  2]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [23]:
def get_unique_rows(X):
    unique_list = []
    i = 0
    while i < len(X):
        row = list(X[i])
        if row not in unique_list:
            unique_list.append(row)
        i += 1
    X_unique = np.unique(unique_list, axis=0) # rows [0], columns [1]
    return X_unique

In [24]:
X = np.random.randint(4, 6, size=(10,3)) #10 rows 3 columns
print(X)

[[4 4 5]
 [5 5 5]
 [4 4 5]
 [5 5 4]
 [4 4 5]
 [5 5 4]
 [4 5 5]
 [4 4 4]
 [4 4 4]
 [4 5 5]]


In [25]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 4, 5],
       [4, 5, 5],
       [5, 5, 4],
       [5, 5, 5]])